# Generated by Django 4.1.7 on 2023-02-27 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('city', models.CharField(choices=[('ISTANBUL', 'İstanbul'), ('TRABZON', 'Trabzon'), ('ANKARA', 'Ankara')], max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('facility_name', models.CharField(max_length=30)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_limit', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sessions', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='attended_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
